/*
 * AUTO-GENERATED by cmake/gen_opencl_shim.py — do not edit by hand.
 *
 * OpenCL dlopen shim for Android: forwards OpenCL API calls to the platform
 * driver (Adreno / Mali) loaded with dlopen(), so libwhisperjni.so never gets
 * a DT_NEEDED entry on libOpenCL.so (vendor libs are outside the app linker
 * namespace; dlopen is the only sanctioned access path).
 *
 * If no OpenCL runtime is found, clGetPlatformIDs returns
 * CL_PLATFORM_NOT_FOUND_KHR so backends degrade gracefully to CPU.
 */

#ifndef CL_TARGET_OPENCL_VERSION
#define CL_TARGET_OPENCL_VERSION 300
#endif
#ifndef CL_PLATFORM_NOT_FOUND_KHR
#define CL_PLATFORM_NOT_FOUND_KHR ((cl_int)-1001)
#endif

#include <CL/cl.h>
#include <dlfcn.h>
#include <pthread.h>

#ifdef __ANDROID__
#include <android/log.h>
#define SHIM_LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "opencl-shim", __VA_ARGS__)
#define SHIM_LOGI(...) __android_log_print(ANDROID_LOG_INFO, "opencl-shim", __VA_ARGS__)
#else
#include <stdio.h>
#define SHIM_LOGE(...) do { fprintf(stderr, __VA_ARGS__); } while (0)
#define SHIM_LOGI(...) do { fprintf(stderr, __VA_ARGS__); } while (0)
#endif

static const char *const kOpenLibCandidates[] = {
    "libOpenCL.so",
    "/vendor/lib64/libOpenCL.so",
    "/system/vendor/lib64/libOpenCL.so",
    "/odm/lib64/libOpenCL.so",
    "/system/lib64/egl/libOpenCL.so",
    "/system/lib64/libOpenCL.so",
    // last resort: some stacks expose the driver itself (it may be the
    // full CL implementation rather than a dependency-only lib)
    "/vendor/lib64/libOpenCL_adreno.so",
    "/odm/lib64/libOpenCL_adreno.so",
};

static void *g_opencl_lib = NULL;
static int g_load_attempted = 0;
static int g_enabled = 0;

/* Trampoline targets: external linkage + hidden visibility + used, because
 * they are referenced only from inline asm and addressed PC-relative. */
__attribute__((visibility("hidden"), used)) void *g_ptr_clBuildProgram = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateBuffer = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateBufferWithProperties = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateCommandQueue = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateContext = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateImage = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateKernel = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateProgramWithBinary = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateProgramWithSource = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clCreateSubBuffer = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clEnqueueBarrierWithWaitList = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clEnqueueCopyBuffer = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clEnqueueFillBuffer = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clEnqueueMarkerWithWaitList = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clEnqueueNDRangeKernel = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clEnqueueReadBuffer = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clEnqueueWriteBuffer = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clFinish = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clFlush = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clGetDeviceIDs = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clGetDeviceInfo = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clGetKernelWorkGroupInfo = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clGetPlatformIDs = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clGetPlatformInfo = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clGetProgramBuildInfo = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clGetProgramInfo = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clReleaseEvent = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clReleaseKernel = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clReleaseMemObject = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clReleaseProgram = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clSetKernelArg = NULL;
__attribute__((visibility("hidden"), used)) void *g_ptr_clWaitForEvents = NULL;

static void opencl_shim_load(void) {
    for (size_t i = 0; i < sizeof(kOpenLibCandidates) / sizeof(kOpenLibCandidates[0]); i++) {
        const char *cand = kOpenLibCandidates[i];
        void *lib = dlopen(cand, RTLD_NOW | RTLD_LOCAL);
        if (lib != NULL) {
            g_opencl_lib = lib;
            SHIM_LOGI("loaded %s", cand);
            break;
        }
        const char *err = dlerror();
        SHIM_LOGE("dlopen %s failed: %s", cand, err ? err : "unknown error");
    }
    if (g_opencl_lib == NULL) {
        SHIM_LOGE("no OpenCL runtime found: all dlopen candidates failed");
        return;
    }
    g_ptr_clBuildProgram = dlsym(g_opencl_lib, "clBuildProgram");
    if (g_ptr_clBuildProgram == NULL) SHIM_LOGE("missing OpenCL symbol clBuildProgram");
    g_ptr_clCreateBuffer = dlsym(g_opencl_lib, "clCreateBuffer");
    if (g_ptr_clCreateBuffer == NULL) SHIM_LOGE("missing OpenCL symbol clCreateBuffer");
    g_ptr_clCreateBufferWithProperties = dlsym(g_opencl_lib, "clCreateBufferWithProperties");
    if (g_ptr_clCreateBufferWithProperties == NULL) SHIM_LOGE("missing OpenCL symbol clCreateBufferWithProperties");
    g_ptr_clCreateCommandQueue = dlsym(g_opencl_lib, "clCreateCommandQueue");
    if (g_ptr_clCreateCommandQueue == NULL) SHIM_LOGE("missing OpenCL symbol clCreateCommandQueue");
    g_ptr_clCreateContext = dlsym(g_opencl_lib, "clCreateContext");
    if (g_ptr_clCreateContext == NULL) SHIM_LOGE("missing OpenCL symbol clCreateContext");
    g_ptr_clCreateImage = dlsym(g_opencl_lib, "clCreateImage");
    if (g_ptr_clCreateImage == NULL) SHIM_LOGE("missing OpenCL symbol clCreateImage");
    g_ptr_clCreateKernel = dlsym(g_opencl_lib, "clCreateKernel");
    if (g_ptr_clCreateKernel == NULL) SHIM_LOGE("missing OpenCL symbol clCreateKernel");
    g_ptr_clCreateProgramWithBinary = dlsym(g_opencl_lib, "clCreateProgramWithBinary");
    if (g_ptr_clCreateProgramWithBinary == NULL) SHIM_LOGE("missing OpenCL symbol clCreateProgramWithBinary");
    g_ptr_clCreateProgramWithSource = dlsym(g_opencl_lib, "clCreateProgramWithSource");
    if (g_ptr_clCreateProgramWithSource == NULL) SHIM_LOGE("missing OpenCL symbol clCreateProgramWithSource");
    g_ptr_clCreateSubBuffer = dlsym(g_opencl_lib, "clCreateSubBuffer");
    if (g_ptr_clCreateSubBuffer == NULL) SHIM_LOGE("missing OpenCL symbol clCreateSubBuffer");
    g_ptr_clEnqueueBarrierWithWaitList = dlsym(g_opencl_lib, "clEnqueueBarrierWithWaitList");
    if (g_ptr_clEnqueueBarrierWithWaitList == NULL) SHIM_LOGE("missing OpenCL symbol clEnqueueBarrierWithWaitList");
    g_ptr_clEnqueueCopyBuffer = dlsym(g_opencl_lib, "clEnqueueCopyBuffer");
    if (g_ptr_clEnqueueCopyBuffer == NULL) SHIM_LOGE("missing OpenCL symbol clEnqueueCopyBuffer");
    g_ptr_clEnqueueFillBuffer = dlsym(g_opencl_lib, "clEnqueueFillBuffer");
    if (g_ptr_clEnqueueFillBuffer == NULL) SHIM_LOGE("missing OpenCL symbol clEnqueueFillBuffer");
    g_ptr_clEnqueueMarkerWithWaitList = dlsym(g_opencl_lib, "clEnqueueMarkerWithWaitList");
    if (g_ptr_clEnqueueMarkerWithWaitList == NULL) SHIM_LOGE("missing OpenCL symbol clEnqueueMarkerWithWaitList");
    g_ptr_clEnqueueNDRangeKernel = dlsym(g_opencl_lib, "clEnqueueNDRangeKernel");
    if (g_ptr_clEnqueueNDRangeKernel == NULL) SHIM_LOGE("missing OpenCL symbol clEnqueueNDRangeKernel");
    g_ptr_clEnqueueReadBuffer = dlsym(g_opencl_lib, "clEnqueueReadBuffer");
    if (g_ptr_clEnqueueReadBuffer == NULL) SHIM_LOGE("missing OpenCL symbol clEnqueueReadBuffer");
    g_ptr_clEnqueueWriteBuffer = dlsym(g_opencl_lib, "clEnqueueWriteBuffer");
    if (g_ptr_clEnqueueWriteBuffer == NULL) SHIM_LOGE("missing OpenCL symbol clEnqueueWriteBuffer");
    g_ptr_clFinish = dlsym(g_opencl_lib, "clFinish");
    if (g_ptr_clFinish == NULL) SHIM_LOGE("missing OpenCL symbol clFinish");
    g_ptr_clFlush = dlsym(g_opencl_lib, "clFlush");
    if (g_ptr_clFlush == NULL) SHIM_LOGE("missing OpenCL symbol clFlush");
    g_ptr_clGetDeviceIDs = dlsym(g_opencl_lib, "clGetDeviceIDs");
    if (g_ptr_clGetDeviceIDs == NULL) SHIM_LOGE("missing OpenCL symbol clGetDeviceIDs");
    g_ptr_clGetDeviceInfo = dlsym(g_opencl_lib, "clGetDeviceInfo");
    if (g_ptr_clGetDeviceInfo == NULL) SHIM_LOGE("missing OpenCL symbol clGetDeviceInfo");
    g_ptr_clGetKernelWorkGroupInfo = dlsym(g_opencl_lib, "clGetKernelWorkGroupInfo");
    if (g_ptr_clGetKernelWorkGroupInfo == NULL) SHIM_LOGE("missing OpenCL symbol clGetKernelWorkGroupInfo");
    g_ptr_clGetPlatformIDs = dlsym(g_opencl_lib, "clGetPlatformIDs");
    if (g_ptr_clGetPlatformIDs == NULL) SHIM_LOGE("missing OpenCL symbol clGetPlatformIDs");
    g_ptr_clGetPlatformInfo = dlsym(g_opencl_lib, "clGetPlatformInfo");
    if (g_ptr_clGetPlatformInfo == NULL) SHIM_LOGE("missing OpenCL symbol clGetPlatformInfo");
    g_ptr_clGetProgramBuildInfo = dlsym(g_opencl_lib, "clGetProgramBuildInfo");
    if (g_ptr_clGetProgramBuildInfo == NULL) SHIM_LOGE("missing OpenCL symbol clGetProgramBuildInfo");
    g_ptr_clGetProgramInfo = dlsym(g_opencl_lib, "clGetProgramInfo");
    if (g_ptr_clGetProgramInfo == NULL) SHIM_LOGE("missing OpenCL symbol clGetProgramInfo");
    g_ptr_clReleaseEvent = dlsym(g_opencl_lib, "clReleaseEvent");
    if (g_ptr_clReleaseEvent == NULL) SHIM_LOGE("missing OpenCL symbol clReleaseEvent");
    g_ptr_clReleaseKernel = dlsym(g_opencl_lib, "clReleaseKernel");
    if (g_ptr_clReleaseKernel == NULL) SHIM_LOGE("missing OpenCL symbol clReleaseKernel");
    g_ptr_clReleaseMemObject = dlsym(g_opencl_lib, "clReleaseMemObject");
    if (g_ptr_clReleaseMemObject == NULL) SHIM_LOGE("missing OpenCL symbol clReleaseMemObject");
    g_ptr_clReleaseProgram = dlsym(g_opencl_lib, "clReleaseProgram");
    if (g_ptr_clReleaseProgram == NULL) SHIM_LOGE("missing OpenCL symbol clReleaseProgram");
    g_ptr_clSetKernelArg = dlsym(g_opencl_lib, "clSetKernelArg");
    if (g_ptr_clSetKernelArg == NULL) SHIM_LOGE("missing OpenCL symbol clSetKernelArg");
    g_ptr_clWaitForEvents = dlsym(g_opencl_lib, "clWaitForEvents");
    if (g_ptr_clWaitForEvents == NULL) SHIM_LOGE("missing OpenCL symbol clWaitForEvents");
}

/* Opt-in switch: the Adreno OpenCL driver aborts (ggml CL_CHECK) on some OEM
 * builds, which is uncatchable from Java. OpenCL stays disabled until the app
 * explicitly enables it. */
void opencl_shim_set_enabled(int enabled) {
    g_enabled = enabled;
    if (!enabled) g_load_attempted = 0;
}

static int opencl_shim_ensure(void) {
    if (!g_enabled) return 0;
    if (!g_load_attempted) {
        g_load_attempted = 1;
        opencl_shim_load();
    }
    return g_opencl_lib != NULL;
}

/* Typed wrapper: callers probe platform availability; report "not found"
 * cleanly instead of jumping to NULL when no OpenCL runtime exists. */
cl_int clGetPlatformIDs(cl_uint num_entries, cl_platform_id *platforms, cl_uint *num_platforms) {
    if (!opencl_shim_ensure() || g_ptr_clGetPlatformIDs == NULL) {
        if (num_platforms != NULL) *num_platforms = 0;
        return CL_PLATFORM_NOT_FOUND_KHR;
    }
    cl_int (*fn)(cl_uint, cl_platform_id *, cl_uint *) =
        (cl_int (*)(cl_uint, cl_platform_id *, cl_uint *))g_ptr_clGetPlatformIDs;
    return fn(num_entries, platforms, num_platforms);
}

#if defined(__aarch64__)
/* aarch64 tail-jump trampolines */
__asm__(
    ".globl clBuildProgram\n.type clBuildProgram, %function\nclBuildProgram:\n\tadrp x16, g_ptr_clBuildProgram\n\tldr x16, [x16, :lo12:g_ptr_clBuildProgram]\n\tbr x16\n"
    ".globl clCreateBuffer\n.type clCreateBuffer, %function\nclCreateBuffer:\n\tadrp x16, g_ptr_clCreateBuffer\n\tldr x16, [x16, :lo12:g_ptr_clCreateBuffer]\n\tbr x16\n"
    ".globl clCreateBufferWithProperties\n.type clCreateBufferWithProperties, %function\nclCreateBufferWithProperties:\n\tadrp x16, g_ptr_clCreateBufferWithProperties\n\tldr x16, [x16, :lo12:g_ptr_clCreateBufferWithProperties]\n\tbr x16\n"
    ".globl clCreateCommandQueue\n.type clCreateCommandQueue, %function\nclCreateCommandQueue:\n\tadrp x16, g_ptr_clCreateCommandQueue\n\tldr x16, [x16, :lo12:g_ptr_clCreateCommandQueue]\n\tbr x16\n"
    ".globl clCreateContext\n.type clCreateContext, %function\nclCreateContext:\n\tadrp x16, g_ptr_clCreateContext\n\tldr x16, [x16, :lo12:g_ptr_clCreateContext]\n\tbr x16\n"
    ".globl clCreateImage\n.type clCreateImage, %function\nclCreateImage:\n\tadrp x16, g_ptr_clCreateImage\n\tldr x16, [x16, :lo12:g_ptr_clCreateImage]\n\tbr x16\n"
    ".globl clCreateKernel\n.type clCreateKernel, %function\nclCreateKernel:\n\tadrp x16, g_ptr_clCreateKernel\n\tldr x16, [x16, :lo12:g_ptr_clCreateKernel]\n\tbr x16\n"
    ".globl clCreateProgramWithBinary\n.type clCreateProgramWithBinary, %function\nclCreateProgramWithBinary:\n\tadrp x16, g_ptr_clCreateProgramWithBinary\n\tldr x16, [x16, :lo12:g_ptr_clCreateProgramWithBinary]\n\tbr x16\n"
    ".globl clCreateProgramWithSource\n.type clCreateProgramWithSource, %function\nclCreateProgramWithSource:\n\tadrp x16, g_ptr_clCreateProgramWithSource\n\tldr x16, [x16, :lo12:g_ptr_clCreateProgramWithSource]\n\tbr x16\n"
    ".globl clCreateSubBuffer\n.type clCreateSubBuffer, %function\nclCreateSubBuffer:\n\tadrp x16, g_ptr_clCreateSubBuffer\n\tldr x16, [x16, :lo12:g_ptr_clCreateSubBuffer]\n\tbr x16\n"
    ".globl clEnqueueBarrierWithWaitList\n.type clEnqueueBarrierWithWaitList, %function\nclEnqueueBarrierWithWaitList:\n\tadrp x16, g_ptr_clEnqueueBarrierWithWaitList\n\tldr x16, [x16, :lo12:g_ptr_clEnqueueBarrierWithWaitList]\n\tbr x16\n"
    ".globl clEnqueueCopyBuffer\n.type clEnqueueCopyBuffer, %function\nclEnqueueCopyBuffer:\n\tadrp x16, g_ptr_clEnqueueCopyBuffer\n\tldr x16, [x16, :lo12:g_ptr_clEnqueueCopyBuffer]\n\tbr x16\n"
    ".globl clEnqueueFillBuffer\n.type clEnqueueFillBuffer, %function\nclEnqueueFillBuffer:\n\tadrp x16, g_ptr_clEnqueueFillBuffer\n\tldr x16, [x16, :lo12:g_ptr_clEnqueueFillBuffer]\n\tbr x16\n"
    ".globl clEnqueueMarkerWithWaitList\n.type clEnqueueMarkerWithWaitList, %function\nclEnqueueMarkerWithWaitList:\n\tadrp x16, g_ptr_clEnqueueMarkerWithWaitList\n\tldr x16, [x16, :lo12:g_ptr_clEnqueueMarkerWithWaitList]\n\tbr x16\n"
    ".globl clEnqueueNDRangeKernel\n.type clEnqueueNDRangeKernel, %function\nclEnqueueNDRangeKernel:\n\tadrp x16, g_ptr_clEnqueueNDRangeKernel\n\tldr x16, [x16, :lo12:g_ptr_clEnqueueNDRangeKernel]\n\tbr x16\n"
    ".globl clEnqueueReadBuffer\n.type clEnqueueReadBuffer, %function\nclEnqueueReadBuffer:\n\tadrp x16, g_ptr_clEnqueueReadBuffer\n\tldr x16, [x16, :lo12:g_ptr_clEnqueueReadBuffer]\n\tbr x16\n"
    ".globl clEnqueueWriteBuffer\n.type clEnqueueWriteBuffer, %function\nclEnqueueWriteBuffer:\n\tadrp x16, g_ptr_clEnqueueWriteBuffer\n\tldr x16, [x16, :lo12:g_ptr_clEnqueueWriteBuffer]\n\tbr x16\n"
    ".globl clFinish\n.type clFinish, %function\nclFinish:\n\tadrp x16, g_ptr_clFinish\n\tldr x16, [x16, :lo12:g_ptr_clFinish]\n\tbr x16\n"
    ".globl clFlush\n.type clFlush, %function\nclFlush:\n\tadrp x16, g_ptr_clFlush\n\tldr x16, [x16, :lo12:g_ptr_clFlush]\n\tbr x16\n"
    ".globl clGetDeviceIDs\n.type clGetDeviceIDs, %function\nclGetDeviceIDs:\n\tadrp x16, g_ptr_clGetDeviceIDs\n\tldr x16, [x16, :lo12:g_ptr_clGetDeviceIDs]\n\tbr x16\n"
    ".globl clGetDeviceInfo\n.type clGetDeviceInfo, %function\nclGetDeviceInfo:\n\tadrp x16, g_ptr_clGetDeviceInfo\n\tldr x16, [x16, :lo12:g_ptr_clGetDeviceInfo]\n\tbr x16\n"
    ".globl clGetKernelWorkGroupInfo\n.type clGetKernelWorkGroupInfo, %function\nclGetKernelWorkGroupInfo:\n\tadrp x16, g_ptr_clGetKernelWorkGroupInfo\n\tldr x16, [x16, :lo12:g_ptr_clGetKernelWorkGroupInfo]\n\tbr x16\n"
    ".globl clGetPlatformInfo\n.type clGetPlatformInfo, %function\nclGetPlatformInfo:\n\tadrp x16, g_ptr_clGetPlatformInfo\n\tldr x16, [x16, :lo12:g_ptr_clGetPlatformInfo]\n\tbr x16\n"
    ".globl clGetProgramBuildInfo\n.type clGetProgramBuildInfo, %function\nclGetProgramBuildInfo:\n\tadrp x16, g_ptr_clGetProgramBuildInfo\n\tldr x16, [x16, :lo12:g_ptr_clGetProgramBuildInfo]\n\tbr x16\n"
    ".globl clGetProgramInfo\n.type clGetProgramInfo, %function\nclGetProgramInfo:\n\tadrp x16, g_ptr_clGetProgramInfo\n\tldr x16, [x16, :lo12:g_ptr_clGetProgramInfo]\n\tbr x16\n"
    ".globl clReleaseEvent\n.type clReleaseEvent, %function\nclReleaseEvent:\n\tadrp x16, g_ptr_clReleaseEvent\n\tldr x16, [x16, :lo12:g_ptr_clReleaseEvent]\n\tbr x16\n"
    ".globl clReleaseKernel\n.type clReleaseKernel, %function\nclReleaseKernel:\n\tadrp x16, g_ptr_clReleaseKernel\n\tldr x16, [x16, :lo12:g_ptr_clReleaseKernel]\n\tbr x16\n"
    ".globl clReleaseMemObject\n.type clReleaseMemObject, %function\nclReleaseMemObject:\n\tadrp x16, g_ptr_clReleaseMemObject\n\tldr x16, [x16, :lo12:g_ptr_clReleaseMemObject]\n\tbr x16\n"
    ".globl clReleaseProgram\n.type clReleaseProgram, %function\nclReleaseProgram:\n\tadrp x16, g_ptr_clReleaseProgram\n\tldr x16, [x16, :lo12:g_ptr_clReleaseProgram]\n\tbr x16\n"
    ".globl clSetKernelArg\n.type clSetKernelArg, %function\nclSetKernelArg:\n\tadrp x16, g_ptr_clSetKernelArg\n\tldr x16, [x16, :lo12:g_ptr_clSetKernelArg]\n\tbr x16\n"
    ".globl clWaitForEvents\n.type clWaitForEvents, %function\nclWaitForEvents:\n\tadrp x16, g_ptr_clWaitForEvents\n\tldr x16, [x16, :lo12:g_ptr_clWaitForEvents]\n\tbr x16\n"
);
#elif defined(__x86_64__)
/* x86_64 tail-jump trampolines */
__asm__(
    ".globl clBuildProgram\n.type clBuildProgram, @function\nclBuildProgram:\n\tjmp *g_ptr_clBuildProgram(%rip)\n"
    ".globl clCreateBuffer\n.type clCreateBuffer, @function\nclCreateBuffer:\n\tjmp *g_ptr_clCreateBuffer(%rip)\n"
    ".globl clCreateBufferWithProperties\n.type clCreateBufferWithProperties, @function\nclCreateBufferWithProperties:\n\tjmp *g_ptr_clCreateBufferWithProperties(%rip)\n"
    ".globl clCreateCommandQueue\n.type clCreateCommandQueue, @function\nclCreateCommandQueue:\n\tjmp *g_ptr_clCreateCommandQueue(%rip)\n"
    ".globl clCreateContext\n.type clCreateContext, @function\nclCreateContext:\n\tjmp *g_ptr_clCreateContext(%rip)\n"
    ".globl clCreateImage\n.type clCreateImage, @function\nclCreateImage:\n\tjmp *g_ptr_clCreateImage(%rip)\n"
    ".globl clCreateKernel\n.type clCreateKernel, @function\nclCreateKernel:\n\tjmp *g_ptr_clCreateKernel(%rip)\n"
    ".globl clCreateProgramWithBinary\n.type clCreateProgramWithBinary, @function\nclCreateProgramWithBinary:\n\tjmp *g_ptr_clCreateProgramWithBinary(%rip)\n"
    ".globl clCreateProgramWithSource\n.type clCreateProgramWithSource, @function\nclCreateProgramWithSource:\n\tjmp *g_ptr_clCreateProgramWithSource(%rip)\n"
    ".globl clCreateSubBuffer\n.type clCreateSubBuffer, @function\nclCreateSubBuffer:\n\tjmp *g_ptr_clCreateSubBuffer(%rip)\n"
    ".globl clEnqueueBarrierWithWaitList\n.type clEnqueueBarrierWithWaitList, @function\nclEnqueueBarrierWithWaitList:\n\tjmp *g_ptr_clEnqueueBarrierWithWaitList(%rip)\n"
    ".globl clEnqueueCopyBuffer\n.type clEnqueueCopyBuffer, @function\nclEnqueueCopyBuffer:\n\tjmp *g_ptr_clEnqueueCopyBuffer(%rip)\n"
    ".globl clEnqueueFillBuffer\n.type clEnqueueFillBuffer, @function\nclEnqueueFillBuffer:\n\tjmp *g_ptr_clEnqueueFillBuffer(%rip)\n"
    ".globl clEnqueueMarkerWithWaitList\n.type clEnqueueMarkerWithWaitList, @function\nclEnqueueMarkerWithWaitList:\n\tjmp *g_ptr_clEnqueueMarkerWithWaitList(%rip)\n"
    ".globl clEnqueueNDRangeKernel\n.type clEnqueueNDRangeKernel, @function\nclEnqueueNDRangeKernel:\n\tjmp *g_ptr_clEnqueueNDRangeKernel(%rip)\n"
    ".globl clEnqueueReadBuffer\n.type clEnqueueReadBuffer, @function\nclEnqueueReadBuffer:\n\tjmp *g_ptr_clEnqueueReadBuffer(%rip)\n"
    ".globl clEnqueueWriteBuffer\n.type clEnqueueWriteBuffer, @function\nclEnqueueWriteBuffer:\n\tjmp *g_ptr_clEnqueueWriteBuffer(%rip)\n"
    ".globl clFinish\n.type clFinish, @function\nclFinish:\n\tjmp *g_ptr_clFinish(%rip)\n"
    ".globl clFlush\n.type clFlush, @function\nclFlush:\n\tjmp *g_ptr_clFlush(%rip)\n"
    ".globl clGetDeviceIDs\n.type clGetDeviceIDs, @function\nclGetDeviceIDs:\n\tjmp *g_ptr_clGetDeviceIDs(%rip)\n"
    ".globl clGetDeviceInfo\n.type clGetDeviceInfo, @function\nclGetDeviceInfo:\n\tjmp *g_ptr_clGetDeviceInfo(%rip)\n"
    ".globl clGetKernelWorkGroupInfo\n.type clGetKernelWorkGroupInfo, @function\nclGetKernelWorkGroupInfo:\n\tjmp *g_ptr_clGetKernelWorkGroupInfo(%rip)\n"
    ".globl clGetPlatformInfo\n.type clGetPlatformInfo, @function\nclGetPlatformInfo:\n\tjmp *g_ptr_clGetPlatformInfo(%rip)\n"
    ".globl clGetProgramBuildInfo\n.type clGetProgramBuildInfo, @function\nclGetProgramBuildInfo:\n\tjmp *g_ptr_clGetProgramBuildInfo(%rip)\n"
    ".globl clGetProgramInfo\n.type clGetProgramInfo, @function\nclGetProgramInfo:\n\tjmp *g_ptr_clGetProgramInfo(%rip)\n"
    ".globl clReleaseEvent\n.type clReleaseEvent, @function\nclReleaseEvent:\n\tjmp *g_ptr_clReleaseEvent(%rip)\n"
    ".globl clReleaseKernel\n.type clReleaseKernel, @function\nclReleaseKernel:\n\tjmp *g_ptr_clReleaseKernel(%rip)\n"
    ".globl clReleaseMemObject\n.type clReleaseMemObject, @function\nclReleaseMemObject:\n\tjmp *g_ptr_clReleaseMemObject(%rip)\n"
    ".globl clReleaseProgram\n.type clReleaseProgram, @function\nclReleaseProgram:\n\tjmp *g_ptr_clReleaseProgram(%rip)\n"
    ".globl clSetKernelArg\n.type clSetKernelArg, @function\nclSetKernelArg:\n\tjmp *g_ptr_clSetKernelArg(%rip)\n"
    ".globl clWaitForEvents\n.type clWaitForEvents, @function\nclWaitForEvents:\n\tjmp *g_ptr_clWaitForEvents(%rip)\n"
);
#endif
