#!/usr/bin/env python3
"""Generate opencl_shim.c: a dlopen-based forwarding shim for the OpenCL API.

Android apps must NOT DT_NEEDED-link vendor libs (libOpenCL.so lives outside the
app linker namespace), but dlopen() of libOpenCL.so is allowed. This shim defines
every OpenCL entry point ggml-opencl uses as a tail-jump trampoline through a
dlsym-resolved pointer, so ggml links against the shim instead of libOpenCL.

Regenerate: python3 cmake/gen_opencl_shim.py  (writes ../opencl_shim/opencl_shim.c)
Symbols were extracted with llvm-nm from ggml-opencl objects (whisper.cpp v1.9.3).
"""
import os

# clGetPlatformIDs is special-cased as a typed C wrapper that returns
# CL_PLATFORM_NOT_FOUND_KHR when no OpenCL runtime is present.
TYPED = "clGetPlatformIDs"

SYMBOLS = [
    "clBuildProgram",
    "clCreateBuffer",
    "clCreateBufferWithProperties",
    "clCreateCommandQueue",
    "clCreateContext",
    "clCreateImage",
    "clCreateKernel",
    "clCreateProgramWithBinary",
    "clCreateProgramWithSource",
    "clCreateSubBuffer",
    "clEnqueueBarrierWithWaitList",
    "clEnqueueCopyBuffer",
    "clEnqueueFillBuffer",
    "clEnqueueMarkerWithWaitList",
    "clEnqueueNDRangeKernel",
    "clEnqueueReadBuffer",
    "clEnqueueWriteBuffer",
    "clFinish",
    "clFlush",
    "clGetDeviceIDs",
    "clGetDeviceInfo",
    "clGetKernelWorkGroupInfo",
    TYPED,
    "clGetPlatformInfo",
    "clGetProgramBuildInfo",
    "clGetProgramInfo",
    "clReleaseEvent",
    "clReleaseKernel",
    "clReleaseMemObject",
    "clReleaseProgram",
    "clSetKernelArg",
    "clWaitForEvents",
]

def aarch64_asm(sym):
    return (
        f'.globl {sym}\\n.type {sym}, %function\\n{sym}:\\n'
        f'\\tadrp x16, g_ptr_{sym}\\n\\tldr x16, [x16, :lo12:g_ptr_{sym}]\\n\\tbr x16\\n'
    )

def x86_64_asm(sym):
    return (
        f'.globl {sym}\\n.type {sym}, @function\\n{sym}:\\n'
        f'\\tjmp *g_ptr_{sym}(%rip)\\n'
    )

HEADER = f'''/*
 * AUTO-GENERATED by cmake/gen_opencl_shim.py — do not edit by hand.
 *
 * OpenCL dlopen shim for Android: forwards OpenCL API calls to the platform
 * driver (Adreno / Mali) loaded with dlopen(), so libwhisperjni.so never gets
 * a DT_NEEDED entry on libOpenCL.so (vendor libs are outside the app linker
 * namespace; dlopen is the only sanctioned access path).
 *
 * If no OpenCL runtime is found, clGetPlatformIDs returns
 * CL_PLATFORM_NOT_FOUND_KHR so backends degrade gracefully to CPU.
 */

#ifndef CL_TARGET_OPENCL_VERSION
#define CL_TARGET_OPENCL_VERSION 300
#endif
#ifndef CL_PLATFORM_NOT_FOUND_KHR
#define CL_PLATFORM_NOT_FOUND_KHR ((cl_int)-1001)
#endif

#include <CL/cl.h>
#include <dlfcn.h>
#include <pthread.h>

#ifdef __ANDROID__
#include <android/log.h>
#define SHIM_LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "opencl-shim", __VA_ARGS__)
#define SHIM_LOGI(...) __android_log_print(ANDROID_LOG_INFO, "opencl-shim", __VA_ARGS__)
#else
#include <stdio.h>
#define SHIM_LOGE(...) do {{ fprintf(stderr, __VA_ARGS__); }} while (0)
#define SHIM_LOGI(...) do {{ fprintf(stderr, __VA_ARGS__); }} while (0)
#endif

static const char *const kOpenLibCandidates[] = {{
    "libOpenCL.so",
    "/vendor/lib64/libOpenCL.so",
    "/system/vendor/lib64/libOpenCL.so",
    "/odm/lib64/libOpenCL.so",
    "/system/lib64/egl/libOpenCL.so",
    "/system/lib64/libOpenCL.so",
    // last resort: some stacks expose the driver itself (it may be the
    // full CL implementation rather than a dependency-only lib)
    "/vendor/lib64/libOpenCL_adreno.so",
    "/odm/lib64/libOpenCL_adreno.so",
}};

static void *g_opencl_lib = NULL;
static int g_load_attempted = 0;
static int g_enabled = 0;

/* Trampoline targets: external linkage + hidden visibility + used, because
 * they are referenced only from inline asm and addressed PC-relative. */
'''

MIDDLE = '''
static void opencl_shim_load(void) {
    for (size_t i = 0; i < sizeof(kOpenLibCandidates) / sizeof(kOpenLibCandidates[0]); i++) {
        const char *cand = kOpenLibCandidates[i];
        void *lib = dlopen(cand, RTLD_NOW | RTLD_LOCAL);
        if (lib != NULL) {
            g_opencl_lib = lib;
            SHIM_LOGI("loaded %s", cand);
            break;
        }
        const char *err = dlerror();
        SHIM_LOGE("dlopen %s failed: %s", cand, err ? err : "unknown error");
    }
    if (g_opencl_lib == NULL) {
        SHIM_LOGE("no OpenCL runtime found: all dlopen candidates failed");
        return;
    }
'''

FOOTER = '''
/* Opt-in switch: the Adreno OpenCL driver aborts (ggml CL_CHECK) on some OEM
 * builds, which is uncatchable from Java. OpenCL stays disabled until the app
 * explicitly enables it. */
void opencl_shim_set_enabled(int enabled) {
    g_enabled = enabled;
    if (!enabled) g_load_attempted = 0;
}

static int opencl_shim_ensure(void) {
    if (!g_enabled) return 0;
    if (!g_load_attempted) {
        g_load_attempted = 1;
        opencl_shim_load();
    }
    return g_opencl_lib != NULL;
}

/* Typed wrapper: callers probe platform availability; report "not found"
 * cleanly instead of jumping to NULL when no OpenCL runtime exists. */
cl_int clGetPlatformIDs(cl_uint num_entries, cl_platform_id *platforms, cl_uint *num_platforms) {
    if (!opencl_shim_ensure() || g_ptr_clGetPlatformIDs == NULL) {
        if (num_platforms != NULL) *num_platforms = 0;
        return CL_PLATFORM_NOT_FOUND_KHR;
    }
    cl_int (*fn)(cl_uint, cl_platform_id *, cl_uint *) =
        (cl_int (*)(cl_uint, cl_platform_id *, cl_uint *))g_ptr_clGetPlatformIDs;
    return fn(num_entries, platforms, num_platforms);
}
'''

def main():
    root = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.normpath(os.path.join(root, "..", "opencl_shim"))
    os.makedirs(out_dir, exist_ok=True)

    out = [HEADER]
    for s in SYMBOLS:
        if s == TYPED:
            # resolved through the typed wrapper below
            out.append(f'__attribute__((visibility("hidden"), used)) void *g_ptr_{s} = NULL;\n')
        else:
            out.append(f'__attribute__((visibility("hidden"), used)) void *g_ptr_{s} = NULL;\n')
    out.append(MIDDLE)
    for s in SYMBOLS:
        out.append(f'    g_ptr_{s} = dlsym(g_opencl_lib, "{s}");\n')
        out.append(f'    if (g_ptr_{s} == NULL) SHIM_LOGE("missing OpenCL symbol {s}");\n')
    out.append('}\n')
    out.append(FOOTER)

    out.append('\n#if defined(__aarch64__)\n/* aarch64 tail-jump trampolines */\n')
    out.append('__asm__(\n')
    for s in SYMBOLS:
        if s == TYPED:
            continue
        out.append(f'    "{aarch64_asm(s)}"\n')
    out.append(');\n')
    out.append('#elif defined(__x86_64__)\n/* x86_64 tail-jump trampolines */\n')
    out.append('__asm__(\n')
    for s in SYMBOLS:
        if s == TYPED:
            continue
        out.append(f'    "{x86_64_asm(s)}"\n')
    out.append(');\n')
    out.append('#endif\n')

    out_path = os.path.join(out_dir, "opencl_shim.c")
    with open(out_path, "w", newline="\n") as f:
        f.write("".join(out))
    print(f"wrote {out_path} ({len(SYMBOLS)} symbols)")

if __name__ == "__main__":
    main()
